spring.application.name=demo1
spring.datasource.url=jdbc:mysql://localhost:3306/proyecto_infantes
spring.datasource.username=root
spring.datasource.password=MORALES09
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

# 🔑 API Key de Google Gemini (obtén una gratis en aistudio.google.com)
gemini.api.key=AIzaSyBxRC27Hx8TvE6INz2RnTWiKXRR2CPhDOE